b,h = 600,600
FPS = 30

BLACK = [0,0,0]
RED = [200,60,60]
BLUE = [80,160,230]
GREEN = [60,200,60]

PLAYER_LAYER = 5
FX_LAYER = 4
ENEMY_LAYER = 3

PLAYER_SPEED = 3
PLAYER_MAXIMUM_SPEED = 12
PLAYER_ROTATION_CONSTANT = 30
PLAYER_TRANSPARENT_CONSTANT = 100
PLAYER_DODGE_SPEED = 40
PLAYER_DODGE_SPEED_SIN = PLAYER_DODGE_SPEED*0.707
PLAYER_BULLET_RADIO = 0.2
DODGE_DICT = {  
    "w":[0,-PLAYER_DODGE_SPEED],
    "s":[0,PLAYER_DODGE_SPEED],
    "a":[-PLAYER_DODGE_SPEED,0],
    "d":[PLAYER_DODGE_SPEED,0],
    "wa":[-PLAYER_DODGE_SPEED_SIN,-PLAYER_DODGE_SPEED_SIN],
    "wd":[PLAYER_DODGE_SPEED_SIN,-PLAYER_DODGE_SPEED_SIN],
    "as":[-PLAYER_DODGE_SPEED_SIN,PLAYER_DODGE_SPEED_SIN],
    "sd":[PLAYER_DODGE_SPEED_SIN,PLAYER_DODGE_SPEED_SIN]
}

ENEMY_SPAWN_RATE = 2
ENEMY_SHOOTING_RATE = 0.3

MOVE_ANIMATION_IMAGE_SCALE_CONSTANT = 0.03
