b,h = 1000,1000
FPS = 30
BACKGROUND_BLUR_RATE = 100
PLAYER_HEALTH_IMAGE_SIZE = (50,50)
HEALTH_GIVEN_SCORE = 1000

BLACK = [0,0,0]
WHITE = [255,255,255]
RED = [200,60,60]
BLUE = [80,160,230]
GREEN = [60,200,60]
YELLOW = [230,230,60]
PURPLE = [140,110,145]

UI_LAYER = 6
PLAYER_LAYER = 5
FX_LAYER = 4
ENEMY_LAYER = 3

PLAYER_SPEED = 3
PLAYER_MAXIMUM_HEALTH = 5
PLAYER_INVINCIBLE_TIME = 60
PLAYER_MAXIMUM_SPEED = 12
PLAYER_ROTATION_CONSTANT = 30
PLAYER_TRANSPARENT_CONSTANT = 100
PLAYER_DODGE_SPEED = 40
PLAYER_DODGE_SPEED_SIN = PLAYER_DODGE_SPEED*0.707
PLAYER_BULLET_RADIO = 0.2
PLAYER_MODE1_SHOOTING_CD = 0
PLAYER_MODE2_SHOOTING_CD = 30
PLAYER_DODGE_CD = 10
PLAYER_BULLET_NUM_MODE2 = 10
DODGE_DICT = {  
    "w":[0,-PLAYER_DODGE_SPEED],
    "s":[0,PLAYER_DODGE_SPEED],
    "a":[-PLAYER_DODGE_SPEED,0],
    "d":[PLAYER_DODGE_SPEED,0],
    "wa":[-PLAYER_DODGE_SPEED_SIN,-PLAYER_DODGE_SPEED_SIN],
    "wd":[PLAYER_DODGE_SPEED_SIN,-PLAYER_DODGE_SPEED_SIN],
    "as":[-PLAYER_DODGE_SPEED_SIN,PLAYER_DODGE_SPEED_SIN],
    "sd":[PLAYER_DODGE_SPEED_SIN,PLAYER_DODGE_SPEED_SIN]
}

ENEMY_SPAWN_RATE = 1
ENEMY_SHOOTING_RATE = 1.5
ENEMY_BULLET_RADIO = 0.1

MOVE_ANIMATION_IMAGE_SCALE_CONSTANT = 0.03

spawn_list = []

OPTION_GROW_RATIO = 1.4
OPTION_APPEAR_TIME = 20

TRACKING_BULLET_ROTATION = 10